
puts '🌱 Seeding Artists...'

a1 = Artist.create( name:'Álvaro Suárez Vértiz', hometown: 'Lima, Peru', nationality: 'Peruvian', birth: 1949, death: 0, biography: 'The artist Álvaro Suárez Vértiz was born in the district of Chosica, Lima-Peru. He is the son of Germán Suárez Vértiz and María Teresa Reyes Carrillo, both founders of the “Taller Suárez Vértiz” in the Miraflores district of the Peruvian capital. His full name is Álvaro Darío Félix María Suarez Reyes. It is at the request of his father Germán Suárez Vértiz that he bears his first name followed by the two paternal surnames as his stage name.' , life_mission: 'To represent Don Quixote and, in each performance, pays homage to such an outstanding literary figure of Cervantes, which has been the most printed and reproduced book in the history of mankind.', country_id: peru.id)
a2 = Artist.create( name:'Fernando de Szyszlo', hometown: 'Lima, Peru', nationality: 'Peruvian', birth: 1925, death: 2017, biography: 'Fernando de Szyszlo is renowned for his uniquely poetic abstract paintings which portray ancient Peruvian culture in a modernist style. “Cajamarca,” a series of paintings begun in 1959, allude to the execution of the last Inca, Atahualpa, illustrating the way Szyszlo evoked the emotion of an event via color and form rather than literally depicting it.', life_mission: 'Explored shapes and colors linked to the myths of pre-Hispanic culture and later embraced modernizm, while retaining a strong Latin American identity.', country_id: peru.id)
a3 = Artist.create( name:'Pablo Cesar Amaringo', hometown: 'Puerto Libertad, Argentina', nationality: 'Peruvian', birth: 1943, death: 2009, biography: 'He was 10 years old when he first took ayahuasca–a visionary brew used in shamanism. A severe heart illness–and the magical treatment of this via ayahuasca–led Pablo toward the life of a shaman, and he eventually became a powerful curandero–learning the icaros, or healing songs that the ayahuasca brew taught him.', life_mission: 'Devoted his early career as a shaman to healing people. He then pursued painting and teaching others at his Usko-Ayar school.', country_id: peru.id)
a4 = Artist.create( name:'Victor Delfin', hometown: 'Piura, Peru', nationality: 'Peruvian', birth: 1927, death:, biography: 'Delfin studied painting and drawing at the School of Fine Arts in Lima, and, upon graduation, directed the Regional Schools of Art of Puno and Ayacucho. Graphic in analysis, His paintings translate a conceptual dynamic which identifies with and yet is distingished from folk art. Delfin is proud of his place in the unoroken heritage of Peruvian art from pre-Paracan times to present. He has absorbed this influence and incorporated it into his own expression.', life_mission: 'Victor Delfin found the source of his inspiration in the ancient Paracan culture of Peru, part of the broader Incan civilization. His paintings and tapestries of birds reveals the depth of his pre-Hispanic mythological roots.', country_id: peru.id)
a5 = Artist.create( name:'Grimanesa Amorós', hometown: 'Lima, Peru', nationality: 'Peruvian', birth: 1962, death: 0, biography: 'Grimanesa Amorós is an interdisciplinary artist whose interests in the fields of social history, scientific research, and critical theory have greatly influenced her work. She often uses sculpture, video, lighting and sound to create works that illuminate our notions of personal identity and community.', life_mission: 'Amoros utilizes her art as an agent for empowerment to involve viewers from all different backgrounds and communities.', country_id: peru.id)
a6 = Artist.create( name:'Frida Kahlo', hometown: 'Coyoacán, Mexico City, Mexico', nationality: 'Mexican', birth: 1907, death: 1954, biography: 'Frida Kahlo’s soul-bearing self-portraits reflect both the artist’s interiority and the social mythologies that shaped her life in Mexico. Her canvases incorporated aspects of traditional portraiture and of murals', life_mission: 'o carve a pathway for women to express themselves however they choose.', country_id: mexican.id)
a7 = Artist.create( name:'José Clemente Orozco', hometown: 'Ciudad Guzmán, Mexico', nationality: 'Mexican', birth: 1883 , death: 1949, biography: 'Was one of the major muralists during the Mexican Revolution. In spite of losing his left hand and sight in one eye, Orozco persisted in his artistic career, though not without a biting sense of humor and critical eye.', life_mission: "rozco's focus from his earliest works onward centered on human suffering, no doubt a byproduct of the hardships he had suffered and witnessed in his own life." , country_id: mexico.id)
a8 = Artist.create( name:'Diego Rivera', hometown: 'Guanajuato City, Mexico', nationality: 'Mexican', birth: 1886 , death: 1957, biography: 'Diego Rivera pioneered Mexico’s mural movement in the early 20th century with sprawling, detailed narrative scenes that celebrated the country’s Indigenous culture and working class. His large frescoes helped establish the mural movement in Mexican and international art.', life_mission: 'He rebelled against the traditional school of painting and developed a style that combined historical, social, and political ideas. His great body of work reflects cultural changes taking place in Mexico and around the world during the turbulent twentieth century.', country_id: mexico.id)
a9 = Artist.create( name:'Carlos Almaraz', hometown: 'Mexico City, Mexico', nationality: 'Mexican', birth: 1941 , death: 1989, biography: 'Carlos Almaraz was born in Mexico City in 1949 and grew up in Chicago and Los Angeles. He studied at the University of California, Los Angeles, and later earned a Master of Fine Arts degree from Otis College of Art and Design in 1974.', life_mission: 'To bring attention to the Chicano street art to Los Angeles mainstream art community. Almaraz also created murals, banners, and other artworks for César Chávez and the United Farmworkers Union.', country_id: mexico.id)
a10 = Artist.create( name:'Gabriel Orozco', hometown: 'Jalapa, Veracruz, Mexico', nationality: 'Mexican', birth: 1962 , death: 0, biography: "Gabriel Orozco’s diverse practice—which includes sculpture, photography, painting, and video—often embraces complex geometries, familiar materials, and an element of whimsy or chance.', life_mission: 'He pushes the limits of traditional artistic media - such as sculpture, painting, and photography - testing the traditional rules and techniques that artists have adhered to throughout previous generations, questioning their relevance for today's rapidly changing social realities.", country_id: mexico.id)
a11 = Artist.create( name:'Oscar Murillo', hometown: 'Valle del Cauca, Colombia', nationality: 'Colombian', birth: 1986, death: 0, biography: 'Oscar Murillo leaves his calligraphic, mixed-media canvases on his studio floor to gather dirt and dust; the resulting paintings explore incompletion, transformation, and the realities of maintaining a studio practice. Murillo repurposes discarded scraps of previous works, turning his gestural abstractions into layered palimpsests that meditate on time and process.', life_mission: 'The artist\'s inventive, itinerant practice spans drawing, sculpture, installation, video, and performance and often considers notions of circulation and globalization.', country_id: colombia.id)
a12 = Artist.create( name:'Pedro Ruiz', hometown: 'Bogotá, Colombia', nationality: 'Colombian', birth: 1957, death: 0, biography: 'Pedro Ruiz is today one of Colombia’s most important artists. Knighted by the French Government with the Order of the Arts and Letters and Ambassador to Unicef for his strong commitment to translating his artistic messages into social projects, Ruiz has the ability to connect with the public’s minds and hearts.', life_mission: 'In a poetic and aesthetic manner, this artist addresses political and social issues that have affected him, his country and the world: social displacement, the spraying of drug crops and its effect on nature, aggressive mining and destruction of nature by multinational companies and its effect on the rural population and the contrast between urban and rural living, among other themes.', country_id: colombia.id)
a13 = Artist.create( name:'Monika Bravo', hometown: 'Bogotá, Colombia', nationality: 'Colombian', birth: 1964, death: 0, biography: 'In 1982, Bravo left Bogotá, moving to Rome to study fashion design, which she continued in Paris at Esmod, before traveling to London to study photography. In 1994 she moved to New York. Her work has received acclaim including a 1999 New York Times review which called her piece Synchronicity a 'standout...small, beautifully blurry video images of boats plowing through New York Harbor...'', life_mission: 'Bravo examines the notion of perception by questioning whether the world we live in is but a mental construction; her artistic practice is used as a tool to decipher the laws that govern the world she lives in.', country_id: colombia.id)
a14 = Artist.create( name:'Danilo Dueñas', hometown: 'Cali, Colombia', nationality: 'Colombian', birth: 1956, death: 0, biography: 'Danilo Dueñas has been a Professor at the Art Department of the University of the Andes, the School of Fine Arts of the National University of Colombia and at the Faculty of Fine Arts f the Jorge Tadeo Lozano University since 1990.', life_mission: 'His artwork produces jarring juxtapositions of materials, usually discarded ones, and processes that negotiate between accretion and subtraction without hiding the means of assembly.', country_id: colombia.id)
a15 = Artist.create( name:'Miguel Angel Rojas', hometown: 'Bogotá, Colombia', nationality: 'Colombian', birth: 1946, death: 0, biography: 'Rojas is a photographer, painter and architect. He finished his studies in painting at the Fine arts school of the National University of Colombia and in architecture at the University Javeriana.', life_mission: 'His work includes drawing, painting, photography, installations and video and is often related to the sexuality, the marginal culture, the violence and problems involved with drug consumption and production.', country_id: colombia.id)
a16 = Artist.create( name:'Lygia Clark', hometown: 'Belo Horizonte, State of Minas Gerais, Brazil', nationality: 'Brazilian', birth: 1920 , death: 1988 , biography: 'Lygia Clark, a co-founder of the Brazilian Neo-Concrete movement, made abstract, geometric paintings and sculptures that reimagined the relationship between viewer and object.', life_mission: 'The purpose of her art was to appeal to the average, everyday person, not just the bourgeois crowd.', country_id: brazil.id)
a17 = Artist.create( name:'Hélio Oiticica', hometown: 'Rio de Janeiro, State of Rio de Janeiro, Brazil', nationality: 'Brazilian', birth: 1937 , death: 1980 , biography: 'A prominent figure in the modernist Brazilian avant-garde of the 1950s and ’60s, Hélio Oiticica produced paintings in the Neo-Constructivist style of geometric abstraction, experimenting with color, form, and material.', life_mission: 'The name ‘Tropicália’ was coined by artist Hélio Oiticica. He used it for the title an artwork he first exhibited in Rio de Janeiro in 1967. The word was intended to play on stereotypes of Brazil as a tropical paradise.', country_id: brazil.id)
a18 = Artist.create( name:'Antônio Maluf', hometown: ' São Paulo, State of São Paulo, Brazil', nationality: 'Brazilian', birth: 1926 , death: 2005 , biography: 'The artist used various supports and painted murals and modular elements', life_mission: "I admire Concretist art because it is objective. It's independent. The plastic resource is taken a priori, and a form is constructed in a casual way, based on an entirely plastic language", country_id: brazil.id)
a19 = Artist.create( name:'Romero Britto', hometown: 'Recife, State of Pernambuco, Brazil', nationality: 'Brazilian', birth: 1963 , death: 0 , biography: ' Britto lived and grew up among a big family of eight brothers and sisters. However, his innate creativity allowed Britto to fill his life with images of a bigger and more beautiful world beyond his own at an early age, he painted what he saw and what he imagined on surfaces such as newspapers, cardboard or any scraps that he could find.', life_mission: 'Britto is the founder of the Happy Art Movement, a "visual language of love, hope and happiness" that raises support for St. Jude and puts smiles on the faces of patients.', country_id: brazil.id)
a20 = Artist.create( name:'Alfredo Volpi', hometown: 'Lucca, Italy', nationality: 'Brazilian', birth: 1896 , death: 1988, biography: 'The prominent 20th century painter Alfredo Volpi blurred the boundaries between abstraction and figuration in his geometrically patterned canvases. The Italian-born artist was self-taught, but his oeuvre bears the influence of Impressionism and Expressionism.', life_mission: 'His painting demands the clarity which the requirement of fine composition conceals, that fine composition which he eliminates or, better, ignores, but which that informality of the School of Paris, so appreciated by us, insisted on maintaining, though disguised.', country_id: brazil.id)

puts '🌱 Seeding Users...'

rodney = User.create(name: 'Rodney Payamps', country_of_origin: 'U.S.A', nationality: 'Dominican', age: 25 , life_mission: 'to eat platanos', country_id: dominican.id )
miguel = User.create(name: 'Miguel Nazario', country_of_origin: 'U.S.A', nationality: 'Peruvian', age: 22 , life_mission: 'to represent queer latinx artists', country_id: peru.id )
# u3 = User.create(name: '', country_of_origin: '', nationality: '', age: , life_mission: '')
# u4 = User.create(name: '', country_of_origin: '', nationality: '', age: , life_mission: '')
# u5 = User.create(name: '', country_of_origin: '', nationality: '', age: , life_mission: '')

# puts '🌱 Seeding Artworks...'

# aw1 = Artwork.create(title: '', image: '', category: '', date: , current_lcation: '', artist_id: 1, country_id: , user_id: )
# aw2 = Artwork.create(title: '', image: '', category: '', date: , current_lcation: '', artist_id: 1, country_id: , user_id: )
# aw3 = Artwork.create(title: '', image: '', category: '', date: , current_lcation: '', artist_id: 1 , country_id: , user_id: )
# aw4 = Artwork.create(title: '', image: '', category: '', date: , current_lcation: '', artist_id: 1, country_id: , user_id: )
# aw5 = Artwork.create(title: '', image: '', category: '', date: , current_lcation: '', artist_id: 1, country_id: , user_id: )

puts '🌱 Seeding Countries...'

peru = Country.create(name: 'Peru')
mexican = Country.create(name: 'Mexican')
colombia = Country.create(name: 'Colombia')
brazil = Country.create(name: 'Brazil')
dominican = Country.create(name: 'Dominican Republic')

puts '✅ Done seeding'